p2m-message-server:
  server:
    port: 80
    path: /messages
    interval: 60000

  database:
    username: thinknet
    password: p2m13456
    database: p2m_message_server
    host: localhost
    dialect: mysql

  jpush:
    appKey:
    masterSecret:
